### ISSUE TITLE
Cannot parse old-style begin…end initialization section

### ISSUE THREAD

**Issue by ayeseeem** [pasdoc/pasdoc#155]
I have some old Delphi 6 era code. Some of these files have an initialization section that uses `begin`… `end.` rather than the more modern `initialization` keyword.

PasDoc fails to parse these files with `Unexpected reserved keyword “begin” while parsing unit`.
I cannot tell: is this a bug, or a known limitation of PasDoc?

Note, this only happens when I use the `—implementation-comments` option.

**Comment by Fr0sT-Brutal** [comment]
Fixing this will likely be a hassle with no significant profit. Do you have ability to modify these files?

**Comment by michaliskambi** [comment]
I say we should fix it on PasDoc side. We are committed to parsing everything that Delphi/FPC are parsing. And we have lots of such "tiny details" and we always try to handle them :)

That said, with my quick test, it seems to be working fine:

a.pas

```pascal
unit a;
interface

procedure Foo;

implementation

{ My amazing proc. }
procedure Foo;
begin
end;

begin
end.
```

Processing with PasDoc works OK, no parsing error, and I see proper comment at `Foo` routine:

```
pasdoc --implementation-comments=join a.pas
```

Please submit a testcase to reproduce the problem, and we'll try to fix it :)

**Comment by ayeseeem** [comment]
> Fixing this will likely be a hassle with no significant profit. Do you have ability to modify these files?

Yes, I could modify them if all else fails. I might have to do some tedious $IFDEF magic on 50+ files, but I could manage 😀

**Comment by ayeseeem** [comment]
> ```
> pasdoc --implementation-comments=join a.pas
> ```
> 
> Please submit a testcase to reproduce the problem, and we'll try to fix it :)

thank you, I did spend some time trying to find a minimal test case… but in fact your example above does indeed fail when I try it. I’m using v0.16.0, on Windows.

**Comment by ayeseeem** [comment]
> > ```
> > pasdoc --implementation-comments=join a.pas
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please submit a testcase to reproduce the problem, and we'll try to fix it :)
> 
> 
> thank you, I did spend some time trying to find a minimal test case… but in fact your example above does indeed fail when I try it. I’m using v0.16.0, on Windows.

And if I remove the final `begin` and `end.` from your example, I still get an error, but a different one: “Unexpected end of stream while parsing unit”. So now I’m very confused. I shall do some more testing.

**Comment by Fr0sT-Brutal** [comment]
That's weird.
PasDoc_Parser.pas / TParser.ParseImplementationSection #1860 is the only line mentioning initialization and it is
```
                { Stop parsing on "initialization", "finalization".
                  The "begin" at this point is equivalent to "initialization". }
                KEY_BEGIN, KEY_INITIALIZATION, KEY_FINALIZATION:
                  Break;
```
so parser should 
Probably you have some defines there that PasDoc isn't aware of?

**Comment by ayeseeem** [comment]
OK, I think I'm getting somewhere: it's a version issue?
 
Using the 0.16.0 release, as downloaded from the website, it fails:

```
PasDoc\bin\pasdoc.exe --implementation-comments=join Example.pas
PasDoc 0.16.0 [2021-02-07|FPC 3.2.0|MSWindows|64]
Documentation generator for Pascal source

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Info[1]:    Starting Source File Parsing ...
Info[2]:    Now parsing file Example.pas...
Warning[2]: Error EPasDoc: Example.pas(13): Unexpected reserved word "begin" while parsing unit Example.pas, continuing...
Info[2]:    ... 1 Source File(s) parsed
Fatal Error: EPasDoc: At least one unit must have been successfully parsed to write docs
```

But if I use the latest code from GitHub - which reports the same version 0.16.0? - it works:

```
GitHub\pasdoc\pasdoc\source\console\pasdoc.exe --implementation-comments=join Example.pas
PasDoc 0.16.0 [2021-02-07|FPC 3.2.2|MSWindows|64]
Documentation generator for Pascal source

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Info[1]:    Starting Source File Parsing ...
Info[2]:    Now parsing file Example.pas...
Info[2]:    ... 1 Source File(s) parsed
Info[2]:    Creating links ...
Info[2]:    ...  links created
Info[2]:    Expanding descriptions (pass 1) ...
Info[2]:    Expanding descriptions (pass 2) ...
Info[2]:    ... Descriptions expanded
Info[2]:    Writing Docs for unit "a"
Info[1]:    Done
```

**Comment by michaliskambi** [comment]
@ayeseeem Looks like I fixed it almost 2 years ago, by this commit: https://github.com/pasdoc/pasdoc/commit/e74bed4d51ac4821b4f003afde6fc1bcf1559e65 . It exactly allows to tolerate `begin` instead of `initialization`.

That fix happened ~month after last 0.16.0 release (which was at 2021-02-07, and the fix was on 2021-03-04).

So, everything is good, this is already fixed -- and we should release next version of PasDoc to have the fix actually easily available for everyone.
